package com.critmon.pulsecheck.service;

import com.critmon.pulsecheck.model.Monitor;
import com.critmon.pulsecheck.repository.MonitorRepository;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.core.io.ClassPathResource;
import org.springframework.util.FileCopyUtils;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
@RequiredArgsConstructor
public class MonitorAlertService {

    private static final Logger logger = LoggerFactory.getLogger(MonitorAlertService.class);
    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final MonitorRepository monitorRepository;
    private final EmailService emailService;

    private String loadEmailTemplate() {
        try {
            ClassPathResource resource = new ClassPathResource("templates/email/monitor-expired.html");
            byte[] bytes = FileCopyUtils.copyToByteArray(resource.getInputStream());
            return new String(bytes, StandardCharsets.UTF_8);
        } catch (IOException e) {
            logger.error("Failed to load email template", e);
            return getDefaultHtmlTemplate();
        }
    }

    private String getDefaultHtmlTemplate() {
        return "<html><body>" +
            "<h2>🚨 CRITICAL MONITOR ALERT</h2>" +
            "<p>Device <strong>{{deviceId}}</strong> has expired.</p>" +
            "<p>Monitor ID: {{monitorId}}</p>" +
            "<p>Last Heartbeat: {{lastHeartbeat}}</p>" +
            "<p>Expected Before: {{expiresAt}}</p>" +
            "<p>Timeout: {{timeout}} seconds</p>" +
            "<hr>" +
            "<p><small>This alert was generated by CritMon Pulse Check System</small></p>" +
            "</body></html>";
    }


    @Scheduled(fixedRate = 30000) // 30 seconds
    public void checkExpiredMonitors() {
        logger.debug("Checking for expired monitors...");
        List<Monitor> expiredMonitors = monitorRepository.findExpiredMonitors();
        
        if (expiredMonitors.isEmpty()) {
            logger.debug("📧 EMAIL CHECK: No expired monitors found");
        }
        
        for (Monitor monitor : expiredMonitors) {
            logger.warn("Monitor expired: {} (Device: {})", monitor.getId(), monitor.getDeviceId());
            logger.warn("Expiration details - Last heartbeat: {}, Expires at: {}, Current time: {}, Timeout: {}s", 
                       monitor.getLastHeartbeat(), monitor.getExpiresAt(), java.time.LocalDateTime.now(), monitor.getTimeout());
            
            // Load and customize HTML template
            String template = loadEmailTemplate();
            String htmlContent = template
                .replace("{{deviceId}}", monitor.getDeviceId())
                .replace("{{monitorId}}", monitor.getId())
                .replace("{{lastHeartbeat}}", monitor.getLastHeartbeat().format(formatter))
                .replace("{{expiresAt}}", monitor.getExpiresAt().format(formatter))
                .replace("{{timeout}}", String.valueOf(monitor.getTimeout()))
                .replace("{{alertTime}}", java.time.LocalDateTime.now().format(formatter));
            
            // Send HTML email alert
            String subject = "🚨 CRITICAL: Monitor Expired - " + monitor.getDeviceId();
            
            logger.info("📧 SENDING HTML EMAIL ALERT to {} for device {}", 
                       monitor.getAlertEmail(), monitor.getDeviceId());
            emailService.sendHtmlAlert(monitor.getAlertEmail(), subject, htmlContent);
            logger.info("✅ HTML EMAIL SENT: Alert sent for device {}", monitor.getDeviceId());
            
            // Mark monitor as inactive to prevent duplicate alerts
            monitor.setActive(false);
            monitorRepository.save(monitor);
        }
    }
}
